# Generated by Django 3.2 on 2022-03-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
