# Generated by Django 3.2 on 2022-03-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
