# Generated by Django 3.2 on 2022-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
