# Generated by Django 3.2 on 2022-03-24 21:46

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('dark_mode', models.BooleanField()),
                ('profile_picture', cloudinary.models.CloudinaryField(default='profile_pic_placeholder', max_length=255, verbose_name='profile_pic')),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='favorite_categories', to='wall.Category')),
                ('saved_posts', models.ManyToManyField(blank=True, related_name='favorite_categories', to='wall.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
